#ifndef PUSHA_ERROR_H__
#define PUSHA_ERROR_H__

#include "ece.h"

#define ERROR_INIT_NUMBER				ECE_ERROR_DECRYPT_TRUNCATED
#define PUSHA_ERROR_INVALID_KEY			(ERROR_INIT_NUMBER - 1)
#define PUSHA_ERROR_OPEN_FILE			(ERROR_INIT_NUMBER - 2)
#define PUSHA_ERROR_WRITE_KEY			(ERROR_INIT_NUMBER - 3)
#define PUSHA_ERROR_ENCODE_SUB64		(ERROR_INIT_NUMBER - 4)
#define PUSHA_ERROR_WRONG_ARGUMENTS		(ERROR_INIT_NUMBER - 5)
#define PUSHA_ERROR_INVALID_ENDPOINT	(ERROR_INIT_NUMBER - 6)
#define PUSHA_ERROR_DECODE_SUBSCRIPTION	(ERROR_INIT_NUMBER - 7)
#define PUSHA_ERROR_GENERATE_VAPID		(ERROR_INIT_NUMBER - 8)
#define PUSHA_ERROR_MAKE_PAYLOAD		(ERROR_INIT_NUMBER - 9)
#define PUSHA_ERROR_MAKE_HTTP_HEADERS	(ERROR_INIT_NUMBER - 10)
#define PUSHA_ERROR_MAKE_HTTP_REQUEST	(ERROR_INIT_NUMBER - 11)
#define PUSHA_ERROR_SERIALIZE_HTTP_REQUEST (ERROR_INIT_NUMBER - 12)
#define PUSHA_ERROR_CONNECT				(ERROR_INIT_NUMBER - 13)
#define PUSHA_ERROR_SSL_CREATE			(ERROR_INIT_NUMBER - 14)
#define PUSHA_ERROR_SSL_CONNECT			(ERROR_INIT_NUMBER - 15)
#define PUSHA_ERROR_SSL_SEND			(ERROR_INIT_NUMBER - 16)
#define PUSHA_ERROR_SSL_RECEIVE			(ERROR_INIT_NUMBER - 17)

#endif /* PUSHA_ERROR_H__ */
